RPMWEB/RPMWEB/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

RPMWEB/main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.path_home),
    path('<page>', views.get_page, name='get-page'),
    ]

RPMWEB/main/models.py
from django.db import models

class Person(models.Model):

    first_name = models.CharField("Имя", max_length=30)

    last_name = models.CharField("Фамилия", max_length=30)

    group = models.CharField("Группа", max_length=6)

    email = models.EmailField("Адресс электронной почты", max_length=254)

    test_level = models.IntegerField("Уровень способностей")

class Work(models.Model):

    work_description = models.TextField("Описание работы", max_length=250)

    required_level = models.IntegerField("Требуемый уровень")

    reward = models.CharField("Награда", max_length=30)

class Test(models.Model):

    test_description = models.TextField("Описание теста", max_length=250)

    required_level = models.IntegerField("Требуемый уровень")

    resulting_level = models.IntegerField("Получаемый уровень")

RPMWEB/main/views.py
from django.shortcuts import render
from django.http import HttpResponseNotFound , HttpResponseRedirect

path_list = {
    'home' : 'main/home.html',
    'cabinet' : 'main/cabinet.html',
    'works' : 'main/works.html',
    'examination' : 'main/examination.html',
    'feedback' : 'main/feedback.html',
    'about' : 'main/about.html',
             }


def get_page(request, page):

    path_way = path_list.get(page, None)

    combined_list = [('Главная страница' , 'home'),
                     ('Личный кабинет' , 'cabinet'),
                     ('Работы' , 'works'),
                     ('Тесты' , 'examination'),
                    ('Обратная связь' , 'feedback'),
                    ('О нас' , 'about')]
    paths_name = list(path_list)

    context = {
        'combined_list': combined_list,
        'paths_name': paths_name,
        }

    if path_way:
        return render(request, path_way, context=context)
    else:
        return HttpResponseNotFound('Данная страница не найдена')

def path_home(request):
    return HttpResponseRedirect('/home', get_page)

RPMWEB/main/templates/main/about.html
{% extends 'main/layout.html' %}

{% block content %}
    <h1>Про нас</h1>
    <p>Про нас</p>
{% endblock %}
{% block title %}
Про нас
{% endblock %}

RPMWEB/main/templates/main/cabinet.html
{% extends 'main/layout.html' %}

{% block content %}
    <h1>Личный кабинет</h1>
    <p>Данные</p>
{% endblock %}
{% block title %}
{% endblock %}

RPMWEB/main/templates/main/examination.html
{% extends 'main/layout.html' %}

{% block content %}
    <h1>Тесты</h1>
    <p>Примеры</p>
{% endblock %}
{% block title %}
{% endblock %}

RPMWEB/main/templates/main/feedback.html
{% extends 'main/layout.html' %}

{% block content %}
    <h1>Обратная связь</h1>
    <p>Номера</p>
{% endblock %}
{% block title %}
{% endblock %}

RPMWEB/main/templates/main/home.html
{% extends 'main/layout.html' %}

{% block content %}
    <h1>Главная страница</h1>
    <p>Главная страница</p>

    {% include 'main/test.html' %}
{% endblock %}
{% block title %}
Главная страница
{% endblock %}

RPMWEB/main/templates/main/index.html
{% extends 'main/layout.html' %}

{% block content %}
    <h1>Главная страница</h1>
    <p>Главная страница</p>

    {% include 'main/test.html' %}
{% endblock %}
{% block title %}
Главная страница
{% endblock %}

RPMWEB/main/templates/main/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel = "stylesheet" href = "https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css">
    <link rel = "stylesheet" href="{% static 'main/css/main.css' %}">
</head>
<body>
    <aside>
        <img src="{% static 'main/img/rpmlogo.jpg' %}" alt = "RPMWEB">
        <span class="logo">RpmWeb</span>
        <h3>Навигация</h3>
        <ul>
            {% for page_list , slug_list in combined_list %}
            <li><a href="{% url 'main:get-page' page=slug_list %}"> {{ page_list }} </a></li>
            {% endfor %}
            

        </ul>
    </aside>
    <main>
    {% block content %}
    {% endblock %}
    </main>

</body>
</html>

RPMWEB/main/templates/main/test.html
<p>Просто проверка</p>

RPMWEB/main/templates/main/works.html
{% extends 'main/layout.html' %}

{% block content %}
    <h1>Работы</h1>
    <p>Список</p>
{% endblock %}
{% block title %}
{% endblock %}